-- =====================================================
-- Gold Layer - DIM_COUNTRY (SCD Type 2)
-- Combines Region, Country, Currency, Tax masters
-- Hash-based surrogate key for fact table joins
-- =====================================================

CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    COMMENT = 'Country dimension combining region, country, currency and tax attributes for geographic analysis'
AS
SELECT
    -- Surrogate Key (Hash-based for fact table joins)
    SHA2(CONCAT(
        COALESCE(c.COUNTRY_CODE, ''),
        COALESCE(TO_VARCHAR(c.__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS COUNTRY_DIM_KEY,
    
    -- Business Key
    c.COUNTRY_CODE AS COUNTRY_CODE,
    
    -- Country Attributes
    c.COUNTRY_NAME AS COUNTRY_NAME,
    c.PRIMARY_LANGUAGE AS PRIMARY_LANGUAGE,
    c.TIMEZONE AS TIMEZONE,
    c.MARKET_TIER AS MARKET_TIER,
    c.ECOMMERCE_SUPPORTED AS ECOMMERCE_SUPPORTED,
    c.RETAIL_STORE_SUPPORTED AS RETAIL_STORE_SUPPORTED,
    
    -- Region Attributes
    r.REGION_CODE AS REGION_CODE,
    r.REGION_NAME AS REGION_NAME,
    
    -- Currency Attributes
    cu.CURRENCY_CODE AS CURRENCY_CODE,
    cu.CURRENCY_NAME AS CURRENCY_NAME,
    cu.CURRENCY_SYMBOL AS CURRENCY_SYMBOL,
    
    -- Tax Attributes
    t.TAX_CODE AS TAX_CODE,
    t.TAX_TYPE AS TAX_TYPE,
    t.TAX_RATE AS TAX_RATE,
    t.TAX_INCLUSIVE_FLAG AS TAX_INCLUSIVE_FLAG,
    
    -- SCD Type 2 Columns
    c.__BRONZE_LOAD_TS AS EFFECTIVE_START_TS,
    CAST('9999-12-31 23:59:59' AS TIMESTAMP_NTZ) AS EFFECTIVE_END_TS,
    TRUE AS IS_CURRENT,
    
    -- Audit
    c.__BRONZE_LOAD_TS AS __SOURCE_LOAD_TS

FROM SALES_DEV.SILVER.COUNTRY_MASTER c
LEFT JOIN SALES_DEV.SILVER.REGION_MASTER r 
    ON c.REGION_CODE = r.REGION_CODE AND r.IS_VALID_RECORD = TRUE
LEFT JOIN SALES_DEV.SILVER.CURRENCY_MASTER cu 
    ON c.CURRENCY_CODE = cu.CURRENCY_CODE AND cu.IS_VALID_RECORD = TRUE
LEFT JOIN SALES_DEV.SILVER.TAX_MASTER t 
    ON c.TAX_CODE = t.TAX_CODE AND t.IS_VALID_RECORD = TRUE
WHERE c.IS_VALID_RECORD = TRUE;

-- =====================================================
-- Column Comments for Semantic Layer
-- =====================================================
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN COUNTRY_DIM_KEY COMMENT 'Hash-based surrogate key for fact table joins';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN COUNTRY_CODE COMMENT 'ISO country code - business key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN COUNTRY_NAME COMMENT 'Full country name for display';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN PRIMARY_LANGUAGE COMMENT 'Primary spoken language';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN TIMEZONE COMMENT 'Primary timezone identifier';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN MARKET_TIER COMMENT 'Market classification tier for business segmentation';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN ECOMMERCE_SUPPORTED COMMENT 'E-commerce operations enabled flag';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN RETAIL_STORE_SUPPORTED COMMENT 'Physical retail store operations flag';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN REGION_CODE COMMENT 'Geographic region code';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN REGION_NAME COMMENT 'Geographic region name for grouping';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN CURRENCY_CODE COMMENT 'ISO currency code';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN CURRENCY_NAME COMMENT 'Full currency name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN CURRENCY_SYMBOL COMMENT 'Currency display symbol';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN TAX_CODE COMMENT 'Tax configuration code';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN TAX_TYPE COMMENT 'Type of tax (VAT/GST/SALES_TAX)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN TAX_RATE COMMENT 'Tax rate as decimal for calculations';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN TAX_INCLUSIVE_FLAG COMMENT 'Prices include tax flag';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN EFFECTIVE_START_TS COMMENT 'SCD2 record effective start timestamp';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN EFFECTIVE_END_TS COMMENT 'SCD2 record effective end timestamp';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_COUNTRY ALTER COLUMN IS_CURRENT COMMENT 'SCD2 current record indicator';



-- =====================================================
-- Gold Layer - Product Dimension & Bridge Table
-- DIM_PRODUCT: Full hierarchy Category > Family > Model > SKU
-- BRIDGE_PRODUCT_COUNTRY: Many-to-many product-country availability
-- =====================================================

-- =====================================================
-- DIM_PRODUCT - Main Product Dimension
-- Grain: SKU level with denormalized hierarchy
-- =====================================================
CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    COMMENT = 'Product dimension with full hierarchy: Category > Family > Model > SKU for product analytics'
AS
SELECT
    -- Surrogate Key (Hash-based for fact joins)
    SHA2(CONCAT(
        COALESCE(s.SKU_CODE, ''),
        COALESCE(TO_VARCHAR(s.__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS PRODUCT_DIM_KEY,
    
    -- SKU Level (Grain)
    s.SKU_CODE,
    s.VARIANT,
    s.PRICE_TIER,
    s.GLOBAL_LAUNCH_DATE AS SKU_LAUNCH_DATE,
    s.IS_ACTIVE AS SKU_IS_ACTIVE,
    
    -- Model Level
    m.MODEL_CODE,
    m.MODEL_NAME,
    m.LAUNCH_DATE AS MODEL_LAUNCH_DATE,
    m.DISCONTINUE_DATE AS MODEL_DISCONTINUE_DATE,
    m.LIFECYCLE_STATUS,
    
    -- Family Level
    f.FAMILY_CODE,
    f.FAMILY_NAME,
    f.LAUNCH_YEAR AS FAMILY_LAUNCH_YEAR,
    
    -- Category Level
    c.CATEGORY_CODE,
    c.CATEGORY_NAME,
    c.REPORTING_SEGMENT,
    
    -- SCD Type 2 Columns
    s.__BRONZE_LOAD_TS AS EFFECTIVE_START_TS,
    CAST('9999-12-31 23:59:59' AS TIMESTAMP_NTZ) AS EFFECTIVE_END_TS,
    TRUE AS IS_CURRENT,
    
    -- Audit
    s.__BRONZE_LOAD_TS AS __SOURCE_LOAD_TS

FROM SALES_DEV.SILVER.PRODUCT_SKU_MASTER s
JOIN SALES_DEV.SILVER.PRODUCT_MODEL_MASTER m 
    ON s.MODEL_CODE = m.MODEL_CODE AND m.IS_VALID_RECORD = TRUE
JOIN SALES_DEV.SILVER.PRODUCT_FAMILY_MASTER f 
    ON m.FAMILY_CODE = f.FAMILY_CODE AND f.IS_VALID_RECORD = TRUE
JOIN SALES_DEV.SILVER.PRODUCT_CATEGORY_MASTER c 
    ON f.CATEGORY_CODE = c.CATEGORY_CODE AND c.IS_VALID_RECORD = TRUE
WHERE s.IS_VALID_RECORD = TRUE;

-- Column Comments for DIM_PRODUCT
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN PRODUCT_DIM_KEY COMMENT 'Hash-based surrogate key for fact table joins';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN SKU_CODE COMMENT 'Stock keeping unit code - lowest grain';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN VARIANT COMMENT 'SKU variant description (storage/color)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN PRICE_TIER COMMENT 'Pricing tier: Standard/Premium';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN SKU_LAUNCH_DATE COMMENT 'Global SKU launch date';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN SKU_IS_ACTIVE COMMENT 'SKU active status flag';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN MODEL_CODE COMMENT 'Product model identifier';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN MODEL_NAME COMMENT 'Product model display name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN MODEL_LAUNCH_DATE COMMENT 'Model global launch date';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN MODEL_DISCONTINUE_DATE COMMENT 'Model discontinuation date';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN LIFECYCLE_STATUS COMMENT 'Product lifecycle stage: ACTIVE/DISCONTINUED';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN FAMILY_CODE COMMENT 'Product family identifier';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN FAMILY_NAME COMMENT 'Product family display name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN FAMILY_LAUNCH_YEAR COMMENT 'Year product family was launched';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN CATEGORY_CODE COMMENT 'Product category identifier';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN CATEGORY_NAME COMMENT 'Product category display name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN REPORTING_SEGMENT COMMENT 'Financial reporting segment';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN EFFECTIVE_START_TS COMMENT 'SCD2 record effective start';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN EFFECTIVE_END_TS COMMENT 'SCD2 record effective end';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN IS_CURRENT COMMENT 'SCD2 current record indicator';

-- =====================================================
-- BRIDGE_PRODUCT_COUNTRY - Many-to-Many Bridge Table
-- Links products to countries where they are available
-- Prevents row explosion in DIM_PRODUCT
-- =====================================================
CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    COMMENT = 'Bridge table linking products to countries where they are available - many-to-many relationship'
AS
SELECT
    -- Composite Key
    SHA2(CONCAT(
        COALESCE(pa.SKU_CODE, ''),
        COALESCE(pa.COUNTRY_CODE, ''),
        COALESCE(TO_VARCHAR(pa.__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS BRIDGE_KEY,
    
    -- Foreign Keys (for joining to dimensions)
    SHA2(CONCAT(
        COALESCE(pa.SKU_CODE, ''),
        COALESCE(TO_VARCHAR(ps.__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS PRODUCT_DIM_KEY,
    
    SHA2(CONCAT(
        COALESCE(pa.COUNTRY_CODE, ''),
        COALESCE(TO_VARCHAR(cm.__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS COUNTRY_DIM_KEY,
    
    -- Business Keys
    pa.SKU_CODE,
    pa.COUNTRY_CODE,
    
    -- Availability Attributes
    pa.LOCAL_LAUNCH_DATE,
    pa.LOCAL_DISCONTINUE_DATE,
    pa.IS_AVAILABLE,
    
    -- Audit
    pa.__BRONZE_LOAD_TS AS __SOURCE_LOAD_TS

FROM SALES_DEV.SILVER.PRODUCT_COUNTRY_AVAILABILITY pa
JOIN SALES_DEV.SILVER.PRODUCT_SKU_MASTER ps 
    ON pa.SKU_CODE = ps.SKU_CODE AND ps.IS_VALID_RECORD = TRUE
JOIN SALES_DEV.SILVER.COUNTRY_MASTER cm 
    ON pa.COUNTRY_CODE = cm.COUNTRY_CODE AND cm.IS_VALID_RECORD = TRUE
WHERE pa.IS_VALID_RECORD = TRUE;

-- Column Comments for BRIDGE_PRODUCT_COUNTRY
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN BRIDGE_KEY COMMENT 'Unique bridge record key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN PRODUCT_DIM_KEY COMMENT 'Foreign key to DIM_PRODUCT';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN COUNTRY_DIM_KEY COMMENT 'Foreign key to DIM_COUNTRY';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN SKU_CODE COMMENT 'Product SKU business key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN COUNTRY_CODE COMMENT 'Country business key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN LOCAL_LAUNCH_DATE COMMENT 'Country-specific product launch date';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN LOCAL_DISCONTINUE_DATE COMMENT 'Country-specific discontinuation date';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN IS_AVAILABLE COMMENT 'Product availability flag in country';



-- =====================================================
-- Gold Layer - DIM_STORE (SCD Type 2)
-- Store dimension with location and operational attributes
-- =====================================================

CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    COMMENT = 'Store dimension with location and operational attributes for retail analytics'
AS
SELECT
    -- Surrogate Key (Hash-based for fact joins)
    SHA2(CONCAT(
        COALESCE(STORE_CODE, ''),
        COALESCE(TO_VARCHAR(__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS STORE_DIM_KEY,
    
    -- Business Key
    STORE_CODE,
    
    -- Store Attributes
    STORE_NAME,
    FORMAT_CODE,
    LIFECYCLE_STATUS,
    
    -- Location Attributes
    COUNTRY_CODE,
    REGION_CODE,
    STATE_CODE,
    CITY,
    POSTAL_CODE,
    ADDRESS_LINE1,
    LATITUDE,
    LONGITUDE,
    
    -- Tax & Operations
    TAX_JURISDICTION_CODE,
    FLOOR_AREA_SQFT,
    ANNUAL_RENT_USD,
    
    -- Status & Dates
    STORE_OPEN_DATE,
    STORE_CLOSE_DATE,
    IS_ACTIVE,
    
    -- SCD Type 2 Columns
    __BRONZE_LOAD_TS AS EFFECTIVE_START_TS,
    CAST('9999-12-31 23:59:59' AS TIMESTAMP_NTZ) AS EFFECTIVE_END_TS,
    TRUE AS IS_CURRENT,
    
    -- Audit
    __BRONZE_LOAD_TS AS __SOURCE_LOAD_TS

FROM SALES_DEV.SILVER.STORE_MASTER
WHERE IS_VALID_RECORD = TRUE;

-- =====================================================
-- Column Comments for Semantic Layer
-- =====================================================
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN STORE_DIM_KEY COMMENT 'Hash-based surrogate key for fact table joins';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN STORE_CODE COMMENT 'Unique store identifier - business key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN STORE_NAME COMMENT 'Store display name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN FORMAT_CODE COMMENT 'Store format type: MALL/MINI/FLAGSHIP';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN LIFECYCLE_STATUS COMMENT 'Store operational status: ACTIVE/CLOSED';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN COUNTRY_CODE COMMENT 'Country where store is located';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN REGION_CODE COMMENT 'Geographic region code';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN STATE_CODE COMMENT 'State or province code';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN CITY COMMENT 'City name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN POSTAL_CODE COMMENT 'Postal or ZIP code';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN ADDRESS_LINE1 COMMENT 'Street address';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN LATITUDE COMMENT 'Geographic latitude for mapping';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN LONGITUDE COMMENT 'Geographic longitude for mapping';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN TAX_JURISDICTION_CODE COMMENT 'Tax jurisdiction for store location';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN FLOOR_AREA_SQFT COMMENT 'Store floor area in square feet';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN ANNUAL_RENT_USD COMMENT 'Annual rent amount in USD';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN STORE_OPEN_DATE COMMENT 'Date store opened';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN STORE_CLOSE_DATE COMMENT 'Date store closed (if applicable)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN IS_ACTIVE COMMENT 'Store active status flag';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN EFFECTIVE_START_TS COMMENT 'SCD2 record effective start';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN EFFECTIVE_END_TS COMMENT 'SCD2 record effective end';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN IS_CURRENT COMMENT 'SCD2 current record indicator';



-- =====================================================
-- Gold Layer - DIM_CUSTOMER (SCD Type 2)
-- Customer dimension with demographics and loyalty attributes
-- =====================================================

CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    COMMENT = 'Customer dimension with demographics and loyalty attributes for customer analytics'
AS
SELECT
    -- Surrogate Key (Hash-based for fact joins)
    SHA2(CONCAT(
        COALESCE(CUSTOMER_ID, ''),
        COALESCE(TO_VARCHAR(__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS CUSTOMER_DIM_KEY,
    
    -- Business Keys
    CUSTOMER_ID,
    CUSTOMER_NUMBER,
    
    -- Customer Name
    FIRST_NAME,
    LAST_NAME,
    FULL_NAME,
    
    -- Demographics
    GENDER,
    DATE_OF_BIRTH,
    EMAIL,
    PHONE_NUMBER,
    
    -- Address
    STREET_ADDRESS,
    CITY,
    STATE_PROVINCE,
    POSTAL_CODE,
    COUNTRY_CODE,
    COUNTRY_NAME,
    REGION,
    
    -- Preferences & Segmentation
    PREFERRED_LANGUAGE,
    CUSTOMER_SEGMENT,
    LOYALTY_TIER,
    
    -- Status
    REGISTRATION_DATE,
    IS_ACTIVE,
    SOURCE_SYSTEM,
    RECORD_SOURCE,
    
    -- SCD Type 2 Columns
    __BRONZE_LOAD_TS AS EFFECTIVE_START_TS,
    CAST('9999-12-31 23:59:59' AS TIMESTAMP_NTZ) AS EFFECTIVE_END_TS,
    TRUE AS IS_CURRENT,
    
    -- Audit
    __BRONZE_LOAD_TS AS __SOURCE_LOAD_TS

FROM SALES_DEV.SILVER.CUSTOMER_MASTER
WHERE IS_VALID_RECORD = TRUE;

-- =====================================================
-- Column Comments for Semantic Layer
-- =====================================================
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN CUSTOMER_DIM_KEY COMMENT 'Hash-based surrogate key for fact table joins';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN CUSTOMER_ID COMMENT 'Unique customer UUID - business key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN CUSTOMER_NUMBER COMMENT 'Business customer reference number';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN FIRST_NAME COMMENT 'Customer first name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN LAST_NAME COMMENT 'Customer last name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN FULL_NAME COMMENT 'Customer full name for display';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN GENDER COMMENT 'Customer gender';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN DATE_OF_BIRTH COMMENT 'Customer date of birth';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN EMAIL COMMENT 'Customer email address';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN PHONE_NUMBER COMMENT 'Customer phone number';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN STREET_ADDRESS COMMENT 'Customer street address';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN CITY COMMENT 'Customer city';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN STATE_PROVINCE COMMENT 'Customer state or province';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN POSTAL_CODE COMMENT 'Customer postal code';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN COUNTRY_CODE COMMENT 'Customer country code';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN COUNTRY_NAME COMMENT 'Customer country name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN REGION COMMENT 'Geographic region';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN PREFERRED_LANGUAGE COMMENT 'Customer preferred language';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN CUSTOMER_SEGMENT COMMENT 'Customer segment: Consumer/Business';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN LOYALTY_TIER COMMENT 'Loyalty program tier: None/Silver/Gold/Platinum';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN REGISTRATION_DATE COMMENT 'Date customer registered';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN IS_ACTIVE COMMENT 'Customer active status';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN EFFECTIVE_START_TS COMMENT 'SCD2 record effective start';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN EFFECTIVE_END_TS COMMENT 'SCD2 record effective end';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN IS_CURRENT COMMENT 'SCD2 current record indicator';



-- =====================================================
-- Gold Layer - DIM_DATE & FACT_SALES
-- All dynamic tables for full lineage support
-- =====================================================

-- =====================================================
-- DIM_DATE - Calendar Dimension (Dynamic Table)
-- Derived from SILVER.SALES_HEADER date range
-- =====================================================
CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    COMMENT = 'Date dimension derived from sales transaction date range for time-based analytics'
AS
SELECT DISTINCT
    SHA2(TO_VARCHAR(TRANSACTION_TIMESTAMP, 'YYYYMMDD'), 256) AS DATE_DIM_KEY,
    TRANSACTION_TIMESTAMP AS DATE_KEY,
    YEAR(TRANSACTION_TIMESTAMP) AS YEAR_NUMBER,
    QUARTER(TRANSACTION_TIMESTAMP) AS QUARTER_NUMBER,
    MONTH(TRANSACTION_TIMESTAMP) AS MONTH_NUMBER,
    WEEKOFYEAR(TRANSACTION_TIMESTAMP) AS WEEK_NUMBER,
    DAYOFYEAR(TRANSACTION_TIMESTAMP) AS DAY_OF_YEAR,
    DAYOFMONTH(TRANSACTION_TIMESTAMP) AS DAY_OF_MONTH,
    DAYOFWEEK(TRANSACTION_TIMESTAMP) AS DAY_OF_WEEK,
    TO_VARCHAR(TRANSACTION_TIMESTAMP, 'YYYY') AS YEAR_NAME,
    'Q' || QUARTER(TRANSACTION_TIMESTAMP) AS QUARTER_NAME,
    TO_VARCHAR(TRANSACTION_TIMESTAMP, 'MMMM') AS MONTH_NAME,
    TO_VARCHAR(TRANSACTION_TIMESTAMP, 'MON') AS MONTH_SHORT_NAME,
    TO_VARCHAR(TRANSACTION_TIMESTAMP, 'DY') AS DAY_NAME,
    TO_VARCHAR(TRANSACTION_TIMESTAMP, 'YYYY-MM') AS YEAR_MONTH,
    TO_VARCHAR(TRANSACTION_TIMESTAMP, 'YYYY') || '-Q' || QUARTER(TRANSACTION_TIMESTAMP) AS YEAR_QUARTER,
    CASE WHEN MONTH(TRANSACTION_TIMESTAMP) >= 4 THEN YEAR(TRANSACTION_TIMESTAMP) ELSE YEAR(TRANSACTION_TIMESTAMP) - 1 END AS FISCAL_YEAR,
    CASE WHEN MONTH(TRANSACTION_TIMESTAMP) >= 4 THEN QUARTER(TRANSACTION_TIMESTAMP) - 1 ELSE QUARTER(TRANSACTION_TIMESTAMP) + 3 END AS FISCAL_QUARTER,
    CASE WHEN DAYOFWEEK(TRANSACTION_TIMESTAMP) IN (0, 6) THEN TRUE ELSE FALSE END AS IS_WEEKEND,
    FALSE AS IS_HOLIDAY
FROM SALES_DEV.SILVER.SALES_HEADER
WHERE IS_VALID_RECORD = TRUE;

-- Column Comments for DIM_DATE
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN DATE_DIM_KEY COMMENT 'Hash-based surrogate key for fact joins';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN DATE_KEY COMMENT 'Calendar date - business key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN YEAR_NUMBER COMMENT 'Calendar year number';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN QUARTER_NUMBER COMMENT 'Calendar quarter (1-4)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN MONTH_NUMBER COMMENT 'Calendar month (1-12)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN WEEK_NUMBER COMMENT 'Week of year (1-53)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN DAY_OF_YEAR COMMENT 'Day of year (1-366)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN DAY_OF_MONTH COMMENT 'Day of month (1-31)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN DAY_OF_WEEK COMMENT 'Day of week (0=Sun, 6=Sat)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN YEAR_NAME COMMENT 'Year as string';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN QUARTER_NAME COMMENT 'Quarter name (Q1-Q4)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN MONTH_NAME COMMENT 'Full month name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN MONTH_SHORT_NAME COMMENT 'Abbreviated month name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN DAY_NAME COMMENT 'Abbreviated day name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN YEAR_MONTH COMMENT 'Year-Month (YYYY-MM)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN YEAR_QUARTER COMMENT 'Year-Quarter (YYYY-QN)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN FISCAL_YEAR COMMENT 'Fiscal year (Apr-Mar)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN FISCAL_QUARTER COMMENT 'Fiscal quarter (1-4)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN IS_WEEKEND COMMENT 'Weekend flag';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN IS_HOLIDAY COMMENT 'Holiday flag';

-- =====================================================
-- FACT_SALES_HEADER - Transaction Level Fact
-- Grain: One row per transaction
-- =====================================================
CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    COMMENT = 'Sales header fact at transaction grain for transaction-level analytics'
AS
SELECT
    -- Fact Key
    SHA2(CONCAT(
        COALESCE(sh.TRANSACTION_ID, ''),
        COALESCE(TO_VARCHAR(sh.__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS FACT_SALES_HEADER_KEY,
    
    -- Dimension Keys from Gold Layer
    c.CUSTOMER_DIM_KEY,
    s.STORE_DIM_KEY,
    cn.COUNTRY_DIM_KEY,
    d.DATE_DIM_KEY,
    
    -- Degenerate Dimensions
    sh.TRANSACTION_ID,
    sh.TRANSACTION_NUMBER,
    
    -- Transaction Attributes
    sh.TRANSACTION_TIMESTAMP,
    sh.CHANNEL_ID,
    sh.PAYMENT_METHOD,
    sh.CURRENCY,
    
    -- Measures (Additive Facts)
    sh.GROSS_AMOUNT,
    sh.TOTAL_DISCOUNT,
    sh.TOTAL_TAX,
    sh.NET_TOTAL,
    
    -- Count Measure
    1 AS TRANSACTION_COUNT,
    
    -- Audit
    sh.__BRONZE_LOAD_TS AS __SOURCE_LOAD_TS

FROM SALES_DEV.SILVER.SALES_HEADER sh
JOIN SALES_DEV.GOLD.DIM_CUSTOMER c 
    ON sh.CUSTOMER_ID = c.CUSTOMER_ID AND c.IS_CURRENT = TRUE
JOIN SALES_DEV.GOLD.DIM_STORE s 
    ON sh.STORE_ID = s.STORE_CODE AND s.IS_CURRENT = TRUE
JOIN SALES_DEV.GOLD.DIM_COUNTRY cn 
    ON s.COUNTRY_CODE = cn.COUNTRY_CODE AND cn.IS_CURRENT = TRUE
JOIN SALES_DEV.GOLD.DIM_DATE d 
    ON sh.TRANSACTION_TIMESTAMP = d.DATE_KEY
WHERE sh.IS_VALID_RECORD = TRUE;

-- Column Comments for FACT_SALES_HEADER
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN FACT_SALES_HEADER_KEY COMMENT 'Unique transaction fact key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN CUSTOMER_DIM_KEY COMMENT 'Foreign key to DIM_CUSTOMER';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN STORE_DIM_KEY COMMENT 'Foreign key to DIM_STORE';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN COUNTRY_DIM_KEY COMMENT 'Foreign key to DIM_COUNTRY';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN DATE_DIM_KEY COMMENT 'Foreign key to DIM_DATE';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN TRANSACTION_ID COMMENT 'Transaction UUID - degenerate dimension';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN TRANSACTION_NUMBER COMMENT 'Transaction reference number';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN CHANNEL_ID COMMENT 'Sales channel: POS/WEB';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN PAYMENT_METHOD COMMENT 'Payment method used';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN GROSS_AMOUNT COMMENT 'Total before discounts - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN TOTAL_DISCOUNT COMMENT 'Total discount - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN TOTAL_TAX COMMENT 'Total tax - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN NET_TOTAL COMMENT 'Final amount - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN TRANSACTION_COUNT COMMENT 'Count measure for aggregations';

-- =====================================================
-- FACT_SALES_ITEM - Line Item Level Fact
-- Grain: One row per line item
-- References FACT_SALES_HEADER for header context
-- =====================================================
CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    COMMENT = 'Sales item fact at line item grain for product-level analytics'
AS
SELECT
    -- Fact Key
    SHA2(CONCAT(
        COALESCE(si.TRANSACTION_LINE_ID, ''),
        COALESCE(TO_VARCHAR(si.__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS FACT_SALES_ITEM_KEY,
    
    -- Parent Fact Key
    fh.FACT_SALES_HEADER_KEY,
    
    -- Dimension Keys (inherited from header + product)
    fh.CUSTOMER_DIM_KEY,
    p.PRODUCT_DIM_KEY,
    fh.STORE_DIM_KEY,
    fh.COUNTRY_DIM_KEY,
    fh.DATE_DIM_KEY,
    
    -- Degenerate Dimensions
    si.TRANSACTION_LINE_ID,
    fh.TRANSACTION_ID,
    fh.TRANSACTION_NUMBER,
    
    -- Transaction Attributes (from header)
    fh.TRANSACTION_TIMESTAMP,
    fh.CHANNEL_ID,
    fh.CURRENCY,
    
    -- Measures (Additive Facts)
    si.QUANTITY,
    si.UNIT_PRICE,
    si.DISCOUNT_AMOUNT,
    si.TAX_AMOUNT,
    si.LINE_TOTAL,
    
    -- Count Measure
    1 AS LINE_COUNT,
    
    -- Audit
    si.__BRONZE_LOAD_TS AS __SOURCE_LOAD_TS

FROM SALES_DEV.SILVER.SALES_ITEM si
JOIN SALES_DEV.GOLD.FACT_SALES_HEADER fh 
    ON si.TRANSACTION_ID = fh.TRANSACTION_ID
JOIN SALES_DEV.GOLD.DIM_PRODUCT p 
    ON si.SKU_CODE = p.SKU_CODE AND p.IS_CURRENT = TRUE
WHERE si.IS_VALID_RECORD = TRUE;

-- Column Comments for FACT_SALES_ITEM
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN FACT_SALES_ITEM_KEY COMMENT 'Unique line item fact key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN FACT_SALES_HEADER_KEY COMMENT 'Foreign key to FACT_SALES_HEADER';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN PRODUCT_DIM_KEY COMMENT 'Foreign key to DIM_PRODUCT';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN TRANSACTION_LINE_ID COMMENT 'Line item identifier - grain';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN QUANTITY COMMENT 'Quantity sold - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN UNIT_PRICE COMMENT 'Price per unit';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN DISCOUNT_AMOUNT COMMENT 'Line discount - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN TAX_AMOUNT COMMENT 'Line tax - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN LINE_TOTAL COMMENT 'Line total - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN LINE_COUNT COMMENT 'Count measure for line items';

-- =====================================================
-- Gold Layer - Aggregated Fact Tables
-- Pre-computed summaries for dashboard performance
-- =====================================================

-- =====================================================
-- FACT_SALES_DAILY - Daily Grain Aggregation
-- Use for: Daily trends, day-of-week analysis
-- =====================================================
CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_DAILY
    TARGET_LAG = '5 minutes'
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    COMMENT = 'Daily aggregated sales fact for executive dashboards and trend analysis'
AS
SELECT
    -- Date Attributes
    d.DATE_DIM_KEY,
    d.DATE_KEY,
    d.YEAR_NUMBER,
    d.QUARTER_NUMBER,
    d.MONTH_NUMBER,
    d.WEEK_NUMBER,
    d.YEAR_MONTH,
    d.MONTH_NAME,
    d.DAY_NAME,
    d.IS_WEEKEND,
    
    -- Geography
    cn.COUNTRY_DIM_KEY,
    cn.COUNTRY_CODE,
    cn.COUNTRY_NAME,
    cn.REGION_CODE,
    cn.REGION_NAME,
    
    -- Store
    s.STORE_DIM_KEY,
    s.STORE_CODE,
    s.STORE_NAME,
    s.FORMAT_CODE,
    
    -- Channel
    fh.CHANNEL_ID,
    fh.CURRENCY,
    
    -- Measures
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(fh.GROSS_AMOUNT) AS TOTAL_GROSS_AMOUNT,
    SUM(fh.TOTAL_DISCOUNT) AS TOTAL_DISCOUNT,
    SUM(fh.TOTAL_TAX) AS TOTAL_TAX,
    SUM(fh.NET_TOTAL) AS TOTAL_NET_SALES,
    AVG(fh.NET_TOTAL) AS AVG_TRANSACTION_VALUE,
    COUNT(DISTINCT fh.CUSTOMER_DIM_KEY) AS UNIQUE_CUSTOMERS

FROM SALES_DEV.GOLD.FACT_SALES_HEADER fh
JOIN SALES_DEV.GOLD.DIM_DATE d ON fh.DATE_DIM_KEY = d.DATE_DIM_KEY
JOIN SALES_DEV.GOLD.DIM_STORE s ON fh.STORE_DIM_KEY = s.STORE_DIM_KEY
JOIN SALES_DEV.GOLD.DIM_COUNTRY cn ON fh.COUNTRY_DIM_KEY = cn.COUNTRY_DIM_KEY
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21;

-- =====================================================
-- FACT_SALES_WEEKLY - Weekly Grain Aggregation
-- Use for: Week-over-week comparisons, weekly reports
-- =====================================================
CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_WEEKLY
    TARGET_LAG = '7 days'
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    COMMENT = 'Weekly aggregated sales fact for trend analysis and WoW comparisons'
AS
SELECT
    -- Time Period
    d.YEAR_NUMBER,
    d.WEEK_NUMBER,
    MIN(d.DATE_KEY) AS WEEK_START_DATE,
    MAX(d.DATE_KEY) AS WEEK_END_DATE,
    
    -- Geography
    cn.COUNTRY_DIM_KEY,
    cn.COUNTRY_CODE,
    cn.COUNTRY_NAME,
    cn.REGION_CODE,
    cn.REGION_NAME,
    
    -- Channel
    fh.CHANNEL_ID,
    fh.CURRENCY,
    
    -- Measures
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(fh.GROSS_AMOUNT) AS TOTAL_GROSS_AMOUNT,
    SUM(fh.TOTAL_DISCOUNT) AS TOTAL_DISCOUNT,
    SUM(fh.TOTAL_TAX) AS TOTAL_TAX,
    SUM(fh.NET_TOTAL) AS TOTAL_NET_SALES,
    AVG(fh.NET_TOTAL) AS AVG_TRANSACTION_VALUE,
    COUNT(DISTINCT fh.CUSTOMER_DIM_KEY) AS UNIQUE_CUSTOMERS,
    COUNT(DISTINCT fh.STORE_DIM_KEY) AS ACTIVE_STORES,
    COUNT(DISTINCT d.DATE_KEY) AS SELLING_DAYS

FROM SALES_DEV.GOLD.FACT_SALES_HEADER fh
JOIN SALES_DEV.GOLD.DIM_DATE d ON fh.DATE_DIM_KEY = d.DATE_DIM_KEY
JOIN SALES_DEV.GOLD.DIM_COUNTRY cn ON fh.COUNTRY_DIM_KEY = cn.COUNTRY_DIM_KEY
GROUP BY 1,2,5,6,7,8,9,10,11;

-- =====================================================
-- FACT_SALES_MONTHLY - Monthly Grain Aggregation
-- Use for: Executive reporting, MoM/YoY analysis
-- =====================================================
CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_MONTHLY
    TARGET_LAG = '30 days'
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    COMMENT = 'Monthly aggregated sales fact for executive reporting and MoM/YoY analysis'
AS
SELECT
    -- Calendar Time
    d.YEAR_NUMBER,
    d.MONTH_NUMBER,
    d.YEAR_MONTH,
    d.MONTH_NAME,
    d.QUARTER_NUMBER,
    d.YEAR_QUARTER,
    
    -- Fiscal Time
    d.FISCAL_YEAR,
    d.FISCAL_QUARTER,
    
    -- Period Dates
    MIN(d.DATE_KEY) AS MONTH_START_DATE,
    MAX(d.DATE_KEY) AS MONTH_END_DATE,
    
    -- Geography
    cn.COUNTRY_DIM_KEY,
    cn.COUNTRY_CODE,
    cn.COUNTRY_NAME,
    cn.REGION_CODE,
    cn.REGION_NAME,
    
    -- Channel
    fh.CHANNEL_ID,
    fh.CURRENCY,
    
    -- Measures
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(fh.GROSS_AMOUNT) AS TOTAL_GROSS_AMOUNT,
    SUM(fh.TOTAL_DISCOUNT) AS TOTAL_DISCOUNT,
    SUM(fh.TOTAL_TAX) AS TOTAL_TAX,
    SUM(fh.NET_TOTAL) AS TOTAL_NET_SALES,
    AVG(fh.NET_TOTAL) AS AVG_TRANSACTION_VALUE,
    COUNT(DISTINCT fh.CUSTOMER_DIM_KEY) AS UNIQUE_CUSTOMERS,
    COUNT(DISTINCT fh.STORE_DIM_KEY) AS ACTIVE_STORES,
    COUNT(DISTINCT d.DATE_KEY) AS SELLING_DAYS

FROM SALES_DEV.GOLD.FACT_SALES_HEADER fh
JOIN SALES_DEV.GOLD.DIM_DATE d ON fh.DATE_DIM_KEY = d.DATE_DIM_KEY
JOIN SALES_DEV.GOLD.DIM_COUNTRY cn ON fh.COUNTRY_DIM_KEY = cn.COUNTRY_DIM_KEY
GROUP BY 1,2,3,4,5,6,7,8,11,12,13,14,15,16,17;
